# Generated by Django 3.0.6 on 2020-06-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmvpinterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='isNumeric',
        ),
        migrations.AddField(
            model_name='project',
            name='contributing_users',
            field=models.ManyToManyField(to='lmvpinterface.User'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time user created'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('value', models.CharField(blank=True, max_length=128)),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertys', to='lmvpinterface.Commit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
