# Generated by Django 3.0.6 on 2020-06-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmvpinterface', '0003_auto_20200621_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='parent_file',
            new_name='commit',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='parent_file',
            new_name='commit',
        ),
    ]
