# Generated by Django 3.0.6 on 2020-06-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmvpinterface', '0004_auto_20200621_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lmvpinterface_metrics', to='lmvpinterface.Commit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lmvpinterface_propertys', to='lmvpinterface.Commit'),
        ),
    ]
