# Generated by Django 3.0.6 on 2020-06-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmvpinterface', '0005_auto_20200621_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'default_related_name': '%(model_name)ss'},
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='lmvpinterface.User'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='lmvpinterface.Project'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmvpinterface.Commit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmvpinterface.Commit'),
        ),
    ]
