# Generated by Django 3.0.6 on 2020-06-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmvpinterface', '0007_auto_20200621_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='numericmetric',
            options={'default_related_name': '%(model_name)ss'},
        ),
        migrations.AlterModelOptions(
            name='textmetric',
            options={'default_related_name': '%(model_name)ss'},
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmvpinterface.User'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmvpinterface.Project'),
        ),
        migrations.AlterField(
            model_name='numericmetric',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numericmetrics', to='lmvpinterface.Commit'),
        ),
        migrations.AlterField(
            model_name='textmetric',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textmetrics', to='lmvpinterface.Commit'),
        ),
    ]
