# Generated by Django 3.0.8 on 2020-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200801_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
